name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, sqlite3, pdo, pdo_sqlite
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Copy .env
        run: cp .env.example .env
      - name: Set up SQLite database
        run: |
          touch database/database.sqlite
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=database\/database.sqlite/' .env
      - name: Generate JWT secret
        run: php artisan jwt:secret --force
      - name: Run migrations
        run: php artisan migrate --force
      - name: Run tests
        run: vendor/bin/phpunit 